[package]
name = "OK"
version = "0.1.3"
edition = "2024"

[dependencies]
objdiff-core = { version = "2.5.0", features = ["bindings"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
argp = "0.4"
ts-rs = "10.1"

